# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiodataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathername', models.CharField(default='', max_length=200)),
                ('dob', models.DateTimeField()),
                ('marital_status', models.CharField(default='', max_length=200)),
                ('qualification', models.CharField(default='', max_length=1000)),
                ('address', models.CharField(default='', max_length=200)),
                ('old_erp_esic_numbr', models.CharField(default='', max_length=200)),
                ('bank_acnt', models.CharField(default='', max_length=200)),
                ('ifsc_code', models.CharField(default='', max_length=200)),
                ('police_station', models.CharField(default='', max_length=200)),
                ('idnty_mark', models.CharField(default='', max_length=200)),
                ('dateofjoining', models.DateTimeField(default='', max_length=200)),
                ('document_submitted', models.CharField(default='', max_length=200)),
                ('experience', models.CharField(default='', max_length=500)),
                ('preffered_jobs', models.CharField(default='', max_length=500)),
                ('pic', models.FileField(upload_to='profile')),
                ('emailverified', models.BooleanField(default=False)),
                ('timecreated', models.DateTimeField(auto_now_add=True)),
                ('timeupdated', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
